version: "3.7"

x-app: &x-app
  env_file:
    - .env
  volumes:
    - .:/src:cached
    - node_modules:/src/node_modules
    - bundle:/bundle
    - yarn-cache:/usr/local/share/.cache/yarn/v6
    - tmp:/src/tmp
    - log:/src/log
    - ./containers/app/vim:/root/.vim:cached
    - ./tmp/screenshots:/src/tmp/screenshots:delegated
    # exclude from volumes
    - /src/.git
  tty: true
  stdin_open: true

services:
  app:
    <<: *x-app
    build:
      context: .
      target: dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment: &app-env
      PORT: ${RAILS_PORT-3000}
      HOSTS_WHITELIST: ${HOSTS_WHITELIST-""}
    ports:
      - "${RAILS_PORT-3000}:${RAILS_PORT-3000}"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "4432:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
    restart: always

volumes:
  pg_vol:
  bundle:
  yarn-cache:
  node_modules:
  tmp:
  log:
