version: "3.8"

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: "3.1.0-preview1"
        NODE_MAJOR: "16"
        YARN_VERSION: "1.22.15"
    image: rails7_app:1.0.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - .dockerdev/.bashrc:/root/.bashrc:ro
      - .dockerdev/.bashrc:/root/.irbrc:ro
      - node_modules:/node_modules
    environment:
      - RUBY_YJIT_ENABLE=1
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEB_CONCURRENCY=0
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - "3000:3000"
      - "3002:3002"

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"

volumes:
  bundle:
  rails_cache:
  node_modules: