base_url: ''
google:
  gtm_id: 'GTM-P94F8JV'
aws:
  region: 'ap-northeast-1'
  backet_name: ''
slack:
  webhook_url: ''
  contact:
    channel: '#_prod_contact_notifications'
    username: '[prod]お知らせbot'
  post:
    channel: '#_prod_post_notifications'
    username: '[prod]投稿bot'
  error:
    channel: '#_prod_error_notifications'
    username: '[prod]エラーbot'
host: ''
port: 3000