base_url: ''
google:
  gtm_id: 'GTM-HOGEHOGE'
aws:
  region: 'ap-northeast-1'
  backet_name: ''
slack:
  webhook_url: ''
  contact:
    channel: '#_staging_contact_notifications'
    username: '[stg]お知らせbot'
  post:
    channel: '#_staging_post_notifications'
    username: '[stg]投稿bot'
  error:
    channel: '#_staging_error_notifications'
    username: '[stg]エラーbot'
host: ''
port: 3000